### ISSUE TITLE
错误提示globalshare

### ISSUE THREAD

**Issue by axingshow** [xbynet/mdwiki#2]
python3 run.py create_db
/usr/local/lib/python3.5/dist-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.security is deprecated, use flask_security instead.
  .format(x=modname), ExtDeprecationWarning
Traceback (most recent call last):
  File "run.py", line 10, in <module>
    from app import app
  File "/gitproject/mdwiki/app/__init__.py", line 11, in <module>
    from app.factory import create_app
  File "/gitproject/mdwiki/app/factory.py", line 7, in <module>
    from app.util import utilRedis 
  File "/gitproject/mdwiki/app/util/__init__.py", line 24, in <module>
    from . import Constant,globalshare
ImportError: cannot import name 'globalshare'

**Comment by xbynet** [comment]
由于有个文件没有提交所致，已修复，请更新至最新代码，谢谢。
